### ISSUE TITLE
[Enhancement] consider adding tolerations/nodeaffinity configuration

### ISSUE THREAD

**Issue by macgregor** [christian-schlichtherle/synology-csi-chart#2]
First off, thanks a ton for creating this. Great job! Hopefully the synology folks pick it up and run with it.

Many helm charts provide the ability to set tolerations and node affinity of the components they create. For example, if I wanted to make sure the synology-csi controller runs on my control plane nodes and not worker nodes I'd add the following values (particular values are specific to my infrastructure, obviously):
```
# infra nodes have "CriticalAddonsOnly" taint to ensure application workloads arent scheduled there
tolerations:
- key: "CriticalAddonsOnly"
  operator: "Equal"
  value: "true"
  effect: "NoExecute"

# try to schedule on control-plane nodes first
affinity:
  nodeAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: node-role.kubernetes.io/control-plane
          operator: In
          values:
          - 'true'
```

This may even be considered a non-starter for any but the most trivial kubernetes clusters. I'm not sure if some of the synology-csi components are meant to be running on all nodes on a cluster. It seems to be working fine on my two node cluster even though everything is deployed to the worker node due to taints on the master, but im still getting things up and running. 

Here is an example in [oath2-proxy](https://github.com/oauth2-proxy/manifests/blob/main/helm/oauth2-proxy/templates/deployment.yaml#L290).
