### ISSUE TITLE
Default StorageClass entries (synology-csi-delete & synology-csi-retain) always get deployed

### ISSUE THREAD

**Issue by MisterWS** [christian-schlichtherle/synology-csi-chart#9]
I'm trying to work out if this is expected behaviour or not - but when I deploy the Helm chart with a set of custom StorageClasses (e.g. synology-csi-smb), these get deployed **alongside** the default StorageClasses listed in the repo's values.yaml.

The main challenge is that there's no way to get rid of them - so either I have to adjust my naming conventions to match, or I live with additional improperly configured StorageClasses.

Is this what's meant to happen?

**Comment by christian-schlichtherle** [comment]
You can disable them with Helm variables like so:

```
  storageClasses:
    delete:
      disabled: true
    retain:
      disabled: true
```
